# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."anubis-webring-pet" = {
    image = "ghcr.io/techarohq/anubis:main";
    environmentFiles = [ config.sops.secrets.anubis_webring_pet.path ];
    environment = {
      "BIND" = ":8425";
      "COOKIE_DOMAIN" = "webring.pet";
      "POLICY_FNAME" = "/data/cfg/botPolicy.yaml";
      "PUBLIC_URL" = "https://anubis.webring.pet";
      "REDIRECT_DOMAINS" = "*.webring.pet,webring.pet";
      "TARGET" = " ";
    };
    ports = [
      "8425:8425/tcp"
    ];
    volumes = [
      "/home/h4rl/container-data/anubis-webring-pet/botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
    ];
   log-driver = "journald";
    extraOptions = [
      "--network-alias=anubis-webring-pet"
      "--network=anubis-webring-pet_default"
    ];
  };
  systemd.services."podman-anubis-webring-pet" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-anubis-webring-pet_default.service"
    ];
    requires = [
      "podman-network-anubis-webring-pet_default.service"
    ];
    partOf = [
      "podman-compose-anubis-webring-pet-root.target"
    ];
    wantedBy = [
      "podman-compose-anubis-webring-pet-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-anubis-webring-pet_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f anubis-webring-pet_default";
    };
    script = ''
      podman network inspect anubis-webring-pet_default || podman network create anubis-webring-pet_default
    '';
    partOf = [ "podman-compose-anubis-webring-pet-root.target" ];
    wantedBy = [ "podman-compose-anubis-webring-pet-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-anubis-webring-pet-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
