# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."collar" = {
    image = "ghcr.io/h4rldev/collar:latest";
    environmentFiles = [ config.sops.secrets.collar.path ];
    environment = {
      "CACHE_PATH" = "/app/cache/.cache.json";
      "SSL_CERT_FILE" = "/etc/ssl/certs/ca-certificates.crt";
    };
    volumes = [
      "/etc/ssl/certs:/etc/ssl/certs:ro"
      "/home/h4rl/container-data/collar/cache:/app/cache:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "collar";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=collar"
      "--network=collar_default"
    ];
  };
  systemd.services."podman-collar" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-collar_default.service"
    ];
    requires = [
      "podman-network-collar_default.service"
    ];
    partOf = [
      "podman-compose-collar-root.target"
    ];
    wantedBy = [
      "podman-compose-collar-root.target"
    ];
  };
  virtualisation.oci-containers.containers."watchtower-collar" = {
    image = "containrrr/watchtower";
    volumes = [
      "/var/run/podman/podman.sock:/var/run/docker.sock:rw"
    ];
    cmd = [ "--interval" "30" "--scope" "collar" ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "collar";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=watchtower-collar"
      "--network=collar_default"
    ];
  };
  systemd.services."podman-watchtower-collar" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-collar_default.service"
    ];
    requires = [
      "podman-network-collar_default.service"
    ];
    partOf = [
      "podman-compose-collar-root.target"
    ];
    wantedBy = [
      "podman-compose-collar-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-collar_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f collar_default";
    };
    script = ''
      podman network inspect collar_default || podman network create collar_default
    '';
    partOf = [ "podman-compose-collar-root.target" ];
    wantedBy = [ "podman-compose-collar-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-collar-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
