# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."petring-api" = {
    image = "ghcr.io/h4rldev/petring-api:latest";
    environmentFiles = [ config.sops.secrets.petring.path ];
    volumes = [
      "/home/h4rl/container-data/petring/petring-api.toml:/app/petring-api.toml:rw"
      "/home/h4rl/container-data/petring/petring.db:/app/petring.db:rw"
    ];
    ports = [
      "8081:8081/tcp"
    ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "petring-api";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=petring-api"
      "--network=petring_default"
    ];
  };
  systemd.services."podman-petring-api" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-petring_default.service"
    ];
    requires = [
      "podman-network-petring_default.service"
    ];
    partOf = [
      "podman-compose-petring-root.target"
    ];
    wantedBy = [
      "podman-compose-petring-root.target"
    ];
  };  
  virtualisation.oci-containers.containers."petring-web" = {
    image = "ghcr.io/h4rldev/petring-web:latest";
    volumes = [
      "/home/h4rl/container-data/petring/frontend:/app/frontend:rw"
      "/home/h4rl/container-data/petring/petring-web.toml:/app/petring-web.toml:rw"
    ];
    ports = [
      "8080:8080/tcp";
    ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "petring-web";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=petring-web"
      "--network=petring_default"
    ];
  };
  systemd.services."podman-petring-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-petring_default.service"
    ];
    requires = [
      "podman-network-petring_default.service"
    ];
    partOf = [
      "podman-compose-petring-root.target"
    ];
    wantedBy = [
      "podman-compose-petring-root.target"
    ];
  };
  virtualisation.oci-containers.containers."watchtower_petring-api" = {
    image = "containrrr/watchtower";
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    cmd = [ "--interval" "30" "--scope" "petring-api" ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "petring-api";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=watchtower-api"
      "--network=petring_default"
    ];
  };
  systemd.services."podman-watchtower_petring-api" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-petring_default.service"
    ];
    requires = [
      "podman-network-petring_default.service"
    ];
    partOf = [
      "podman-compose-petring-root.target"
    ];
    wantedBy = [
      "podman-compose-petring-root.target"
    ];
  };
  virtualisation.oci-containers.containers."watchtower_petring-web" = {
    image = "containrrr/watchtower";
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    cmd = [ "--interval" "30" "--scope" "petring-web" ];
    labels = {
      "com.centurylinklabs.watchtower.scope" = "petring-web";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=watchtower-web"
      "--network=petring_default"
    ];
  };
  systemd.services."podman-watchtower_petring-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-petring_default.service"
    ];
    requires = [
      "podman-network-petring_default.service"
    ];
    partOf = [
      "podman-compose-petring-root.target"
    ];
    wantedBy = [
      "podman-compose-petring-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-petring_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f petring_default";
    };
    script = ''
      podman network inspect petring_default || podman network create petring_default
    '';
    partOf = [ "podman-compose-petring-root.target" ];
    wantedBy = [ "podman-compose-petring-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-petring-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
