# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."coturn-server" = {
    image = "docker.io/coturn/coturn";
    volumes = [
      "/home/h4rl/container-data/tuwunel/coturn.conf:/etc/coturn/turnserver.conf:rw"
    ];
    cmd = [
      "--min-port=49100"
      "--max-port=49200"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-coturn-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-tuwunel-root.target"
    ];
    wantedBy = [
      "podman-compose-tuwunel-root.target"
    ];
  };
  virtualisation.oci-containers.containers."matrix-rtc-jwt" = {
    image = "ghcr.io/element-hq/lk-jwt-service:latest";
    environmentFiles = [ config.sops.secrets.livekit.path ];
    environment = {
      "LIVEKIT_FULL_ACCESS_HOMESERVERS" = "h4rl.dev";
      "LIVEKIT_JWT_BIND" = ":8018";
      "LIVEKIT_URL" = "wss://matrix-rtc.h4rl.dev";
    };
    log-driver = "journald";
    ports = [
      "8018:8018/tcp"
    ];
    extraOptions = [
      "--network-alias=matrix-rtc-jwt"
      "--network=tuwunel_default"
    ];
  };
  systemd.services."podman-matrix-rtc-jwt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tuwunel_default.service"
    ];
    requires = [
      "podman-network-tuwunel_default.service"
    ];
    partOf = [
      "podman-compose-tuwunel-root.target"
    ];
    wantedBy = [
      "podman-compose-tuwunel-root.target"
    ];
  };
  virtualisation.oci-containers.containers."matrix-rtc-livekit" = {
    image = "livekit/livekit-server:latest";
    volumes = [
      "/home/h4rl/container-data/tuwunel/livekit.yaml:/etc/livekit.yaml:ro"
    ];
    ports = [
      "7880:7880/tcp"
      "7881:7881/tcp"
      "50100:50100/udp"
      "50101:50101/udp"
      "50102:50102/udp"
      "50103:50103/udp"
      "50104:50104/udp"
      "50105:50105/udp"
      "50106:50106/udp"
      "50107:50107/udp"
      "50108:50108/udp"
      "50109:50109/udp"
      "50110:50110/udp"
      "50111:50111/udp"
      "50112:50112/udp"
      "50113:50113/udp"
      "50114:50114/udp"
      "50115:50115/udp"
      "50116:50116/udp"
      "50117:50117/udp"
      "50118:50118/udp"
      "50119:50119/udp"
      "50120:50120/udp"
      "50121:50121/udp"
      "50122:50122/udp"
      "50123:50123/udp"
      "50124:50124/udp"
      "50125:50125/udp"
      "50126:50126/udp"
      "50127:50127/udp"
      "50128:50128/udp"
      "50129:50129/udp"
      "50130:50130/udp"
      "50131:50131/udp"
      "50132:50132/udp"
      "50133:50133/udp"
      "50134:50134/udp"
      "50135:50135/udp"
      "50136:50136/udp"
      "50137:50137/udp"
      "50138:50138/udp"
      "50139:50139/udp"
      "50140:50140/udp"
      "50141:50141/udp"
      "50142:50142/udp"
      "50143:50143/udp"
      "50144:50144/udp"
      "50145:50145/udp"
      "50146:50146/udp"
      "50147:50147/udp"
      "50148:50148/udp"
      "50149:50149/udp"
      "50150:50150/udp"
      "50151:50151/udp"
      "50152:50152/udp"
      "50153:50153/udp"
      "50154:50154/udp"
      "50155:50155/udp"
      "50156:50156/udp"
      "50157:50157/udp"
      "50158:50158/udp"
      "50159:50159/udp"
      "50160:50160/udp"
      "50161:50161/udp"
      "50162:50162/udp"
      "50163:50163/udp"
      "50164:50164/udp"
      "50165:50165/udp"
      "50166:50166/udp"
      "50167:50167/udp"
      "50168:50168/udp"
      "50169:50169/udp"
      "50170:50170/udp"
      "50171:50171/udp"
      "50172:50172/udp"
      "50173:50173/udp"
      "50174:50174/udp"
      "50175:50175/udp"
      "50176:50176/udp"
      "50177:50177/udp"
      "50178:50178/udp"
      "50179:50179/udp"
      "50180:50180/udp"
      "50181:50181/udp"
      "50182:50182/udp"
      "50183:50183/udp"
      "50184:50184/udp"
      "50185:50185/udp"
      "50186:50186/udp"
      "50187:50187/udp"
      "50188:50188/udp"
      "50189:50189/udp"
      "50190:50190/udp"
      "50191:50191/udp"
      "50192:50192/udp"
      "50193:50193/udp"
      "50194:50194/udp"
      "50195:50195/udp"
      "50196:50196/udp"
      "50197:50197/udp"
      "50198:50198/udp"
      "50199:50199/udp"
      "50200:50200/udp"
    ];
    cmd = [ "--config" "/etc/livekit.yaml" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=matrix-rtc-livekit"
      "--network=tuwunel_default"
    ];
  };
  systemd.services."podman-matrix-rtc-livekit" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tuwunel_default.service"
    ];
    requires = [
      "podman-network-tuwunel_default.service"
    ];
    partOf = [
      "podman-compose-tuwunel-root.target"
    ];
    wantedBy = [
      "podman-compose-tuwunel-root.target"
    ];
  };  
  virtualisation.oci-containers.containers."tuwunel-homeserver" = {
    image = "jevolk/tuwunel:latest";
    environmentFiles = [ config.sops.secrets.tuwunel.path ];
    environment = {
      "TUWUNEL_ADDRESS" = "0.0.0.0";
      "TUWUNEL_ALLOW_ENCRYPTION" = "true";
      "TUWUNEL_ALLOW_FEDERATION" = "true";
      "TUWUNEL_ALLOW_INCOMING_PRESENCE" = "true";
      "TUWUNEL_ALLOW_LOCAL_PRESENCE" = "true";
      "TUWUNEL_ALLOW_OUTGOING_PRESENCE" = "true";
      "TUWUNEL_ALLOW_REGISTRATION" = "true";
      "TUWUNEL_CONFIG" = "/etc/tuwunel.toml";
      "TUWUNEL_DATABASE_PATH" = "/var/lib/tuwunel";
      "TUWUNEL_MAX_REQUEST_SIZE" = "50000000";
      "TUWUNEL_PORT" = "8008";
      "TUWUNEL_SERVER_NAME" = "h4rl.dev";
      "TUWUNEL_TRUSTED_SERVERS" = "[\"matrix.org\", \"nixos.org\"]";
      "TUWUNEL_WELL_KNOWN" = "{
  client=https://h4rl.dev,
  server=matrix.h4rl.dev:443
  }
  ";
    };
    volumes = [
      "/home/h4rl/container-data/tuwunel/tuwunel.toml:/etc/tuwunel.toml:rw"
      "tuwunel_db:/var/lib/tuwunel:rw"
    ];
    ports = [
      "8008:8008/tcp"
      "8448:8448/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homeserver"
      "--network=tuwunel_default"
    ];
  };
  systemd.services."podman-tuwunel-homeserver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tuwunel_default.service"
      "podman-volume-tuwunel_db.service"
    ];
    requires = [
      "podman-network-tuwunel_default.service"
      "podman-volume-tuwunel_db.service"
    ];
    partOf = [
      "podman-compose-tuwunel-root.target"
    ];
    wantedBy = [
      "podman-compose-tuwunel-root.target"
    ];
  };
  
  # Networks
  systemd.services."podman-network-tuwunel_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tuwunel_default";
    };
    script = ''
      podman network inspect tuwunel_default || podman network create tuwunel_default
    '';
    partOf = [ "podman-compose-tuwunel-root.target" ];
    wantedBy = [ "podman-compose-tuwunel-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-tuwunel_db" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect tuwunel_db || podman volume create tuwunel_db
    '';
    partOf = [ "podman-compose-tuwunel-root.target" ];
    wantedBy = [ "podman-compose-tuwunel-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tuwunel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
