[pyprland]
plugins = ["magnify", "scratchpads", "workspaces_follow_focus"]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=drop.term"
class = "drop.term"
size = "75% 60%"
max_size = "2560px 100%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[workspaces_follow_focus]
max_workspaces = 4
